server_url = "wss://la-mulana.arakiyda.com/cable"
log_file_name = "lamulanamw.log"
# user_id = 2
# players = { 1 = "Justin", 3 = "Bob" }

log_file_name = "lamulanamw.txt"
game_uid = "73043ade538d32c6263ae9cac303fffd03c9f6b8420f2a5af02f1fca4be3249729023ef20b08e6d3c20c797a0fa6fad264fa00d2a50cccd1716ff9aa0726a92e"
server_url = "ws://192.168.1.100/cable"
user_id = 1
slot = "Lemeza"

[players]
1 = "ausername"
2 = "Test"
