import { Button, ComboBox, HorizontalBox, LineEdit, VerticalBox} from "std-widgets.slint";

export component SeedSelector inherits Window {
    in-out property <[string]> seeds;
    in-out property <string> current-seed;
    in-out property <string> server-url;
    in-out property <string> password;
    in-out property <string> player-name;
    in-out property <string> add-seed-error;
    in-out property <string> load-seed-error;
    in-out property <string> chosen-seed;
    title: "La-Mulana Archipelago Launcher";
    icon: @image-url("../images/lmmw.png");
    height: 310px;
    width: 540px;
    callback close-window();
    callback load();
    callback delete();
    callback add-seed();
    VerticalLayout {
        if !load-seed-error.is-empty: VerticalBox {
            Text {
                text: "\{root.load-seed-error}";
                color: red;
            }
        }
        if seeds.length > 0: HorizontalBox {
            Text {
                text: "Choose Seed:";
                vertical-alignment: center;
                font-weight: 600;
            }
            ComboBox {
                model: seeds;
                current-value: current-seed;
                selected(current-value) => {
                    root.chosen-seed = current-value;
                }
            }
            Button {
                text: "Load";
                height: 30px;
                width: 60px;
                clicked => {
                    root.load()
                }
            }
            Button {
                text: "Delete";
                height: 30px;
                width: 60px;
                clicked => {
                    root.delete()
                }
            }
            Button {
                text: "Cancel";
                height: 30px;
                width: 60px;
                clicked => {
                    root.close-window()
                }
            }
        }
        if seeds.length > 0: VerticalBox {
            padding-top: 20px;
            padding-bottom: 20px;
            Rectangle {
                height: 1px;
                background: #000;
                width: parent.width - 10px;
                x: 5px;
            }
        }
        VerticalBox {
            Text {
                text: "Add New Seed";
                font-weight: 600;
                horizontal-alignment: center;
            }
        }
        if !add-seed-error.is-empty: VerticalBox {
            Text {
                text: "\{root.add-seed-error}";
                color: red;
            }
        }
        HorizontalBox {
            Text {
                text: "Server URL:";
                vertical-alignment: center;
                width: 80px;
            }
            LineEdit {
                placeholder-text: "Server URL With Port";
                edited(value) => {
                    root.server-url = value;
                }
            }
        }
        HorizontalBox {
            Text {
                text: "Password:";
                vertical-alignment: center;
                width: 80px;
            }
            LineEdit {
                placeholder-text: "Password (leave blank if no password)";
                edited(value) => {
                    root.password = value;
                }
            }
        }
        HorizontalBox {
            Text {
                text: "Player Name:";
                vertical-alignment: center;
                width: 80px;
            }
            LineEdit {
                placeholder-text: "Your Player Name";
                edited(value) => {
                    root.player-name = value;
                }
            }
        }
        HorizontalBox {
            Button {
                text: "Add Seed";
                height: 30px;
                width: 100px;
                clicked => {
                    root.add-seed()
                }
            }
            if seeds.length == 0: Button {
                text: "Cancel";
                height: 30px;
                width: 100px;
                clicked => {
                    root.close-window()
                }
            }
        }
    }
}
